### ISSUE TITLE
User Akses Landing Page

### ISSUE THREAD

**Issue by greaserdev** [FTP-YCAB-Fullstack/GP1-Fantastic-Four#4]
Ketika user memasuki website, maka ada 2 section yang di tampilkan, yaitu Now Playing dan Upcoming Film.

- [x] Navigation Bar => Berisi Logo, Now Playing, Upcoming, Top Rated #10 
- [x] Header => Berisi Welcoming Text dan Search Box untuk Informasi Film Global #11 
- [x] Now Playing => Film yang sedang tayang di Indoneisa #13 
- [x] Upcoming => Film yang akan tayang di Indonesia #14 
- [x] Footer => User dapat melihat Footer #12
